S3 output / Plugin support
deepfence/PacketStreamer pull request #11
Opened 2022-04-08 11:25 UTC by r8ygun

2022-04-11 14:49 UTC, vadorovsky requested changes
Thank you for working on this! I really like the plugin system. I would be happy to accept your solution.

I left some comments. Apart from them, I think it would make sense to borrow docs from my PR, but I can also submit them myself later - whatever you prefer.

2022-04-11 22:06 UTC, r8ygun commented on .github/workflows/container-image.yml
> +on:
Yeah, this struck me as really odd, but I didn't want to undo it without asking - will take it out.

2022-04-11 22:12 UTC, r8ygun commented on .github/workflows/container-image.yml
> +on:
Merging upstream removed it so I guess as long as we squash merge when you accept this then we're good?

2022-04-11 22:20 UTC, r8ygun commented on pkg/config/helpers.go
> +package config
Yes, good spot here, I'll change that as it certainly doesn't make any sense where it is.

2022-04-11 23:00 UTC, r8ygun commented on pkg/config/config.go
> +	UploadChunkSize string
Yeah, great idea. Your changes here make a lot of sense, the only one I think we might need to change is 

```
		if rawConfig.Output.S3.TotalFileSize != nil {
			t, err := bytesize.Parse(*rawConfig.Output.S3.TotalFileSize)
			if err != nil {
				return nil, fmt.Errorf("could not parse the totalFileSize field %s: %w", *rawConfig.Output.S3.TotalFileSize, err)
			}
			totalFileSize = &t
		} else {
			t := 1 * bytesize.MB
			totalFileSize = &t
		}
```

if we add `uploadChunkSize` as a parameter, the default of it needs to be 5MB as this is the minimum part size. `totalFileSize` should probably be some multiple of 5.  Maybe only if `uploadChunkSize` is actually set? Maybe we should switch back to `PutObject` for small objects anyway, but this might be outside the scope of this one change?

2022-04-11 23:17 UTC, r8ygun commented on pkg/config/config.go
> +	TotalFileSize   string
Done.

2022-04-11 23:27 UTC, r8ygun commented
@vadorovsky I've submitted the changes you requested - let me know if there's anything else you want to change.  I'll mark this for review in the meantime.

2022-04-14 14:18 UTC, vadorovsky approved these changes
Looks good to me. Thanks for addressing my comments! :pray: 

I'm happy to merge this after squashing into one commit and giving some descriptive commit message.

2022-04-14 14:34 UTC, r8ygun commented
> I'm happy to merge this after squashing into one commit and giving some descriptive commit message.

@vadorovsky Do you mean you want me to squash the commits on my fork, or you're going to do them on your end pre-merge?

2022-04-15 01:17 UTC, closed without merging