Add plugin support for streaming packets to Kafka
deepfence/PacketStreamer pull request #20
Opened 2022-04-21 00:13 UTC by r8ygun

There are some assumptions that I've made in this PR that probably need to be addressed before this can be marked as ready for review.

1. With the S3 Plugin, we added the PCAP header to each file so that the objects in S3 were valid files. It would seem sensible to do the same with Kafka but we might be more constrained.  For example, how do we know when to start a new "file"?  We probably don't want to add the header to every 65 KB message unless we also want files to be that size too, but that seems odd.  Maybe there should be some `fileSize` property and a new header is added to the first packet after `fileSize` amount of data has been received. There will be more work to do if this is the behaviour that you want.
2. Packets that are destined for the same file need to share a message key to guarantee ordering.  I've hard coded this as "packetstreamer" right now, but I'm happy to hear suggestions on other approaches. If we follow the approach suggestion in point 1, we could generate a new value for each "file" that could be used as the key.

2022-04-24 01:43 UTC, vadorovsky requested changes
Thanks a lot for working on that. Looking forward to see the final so look solution! 🙂

2022-04-24 01:43 UTC, vadorovsky commented on contrib/config/receiver-kafka.yaml
> +    path: /dev/null
Do we need to define the file section here at all?

2022-04-24 01:43 UTC, vadorovsky commented on pkg/plugins/kafka/kafka.go
> +	if len(p.Buffer) > 4 {
Why 4? Maybe we should have some constant with a comment for that?

2022-04-24 18:18 UTC, r8ygun commented on pkg/plugins/kafka/kafka.go
> +	if len(p.Buffer) > 4 {
This is very likely to change / be removed. The idea for 4 was to only flush if there's a buffer that contains more than the header length. But yeah, constant / comment will be necessary regardless so thank you.

2022-04-24 23:35 UTC, r8ygun commented on contrib/config/receiver-kafka.yaml
> +    path: /dev/null
Removed.

2022-04-24 23:47 UTC, r8ygun commented
There is now a `fileSize` property that is set in the config. We will read publish each "message" to Kafka, but after `fileSize` amount of data is received, we will start a new "file" (with accompanying header).  Each "file" has its own unique ID that is used as the Kafka message key when publishing packets that will be contained in that "file".

2022-04-25 08:27 UTC, merged

2022-04-25 08:28 UTC, vadorovsky commented
Thanks, LGTM.

We need to do better job with handling errors, but it needs to be done for S3 as well, so I'd be happy to make that change for both plugins at the same time.